<?php
return [
    ['id' => 1, 'first_name' => 'John', 'last_name' => 'Travolta', 'birth_date' => '1954-02-18', 'actor_nationality' => 'USA'],
    ['id' => 2, 'first_name' => 'Samuel L.', 'last_name' => 'Jackson', 'birth_date' => '1948-12-21', 'actor_nationality' => 'USA'],
    ['id' => 3, 'first_name' => 'Uma', 'last_name' => 'Thurman', 'birth_date' => '1970-04-29', 'actor_nationality' => 'USA'],
    ['id' => 4, 'first_name' => 'Leonardo', 'last_name' => 'DiCaprio', 'birth_date' => '1974-11-11', 'actor_nationality' => 'USA'],
    ['id' => 5, 'first_name' => 'Joseph', 'last_name' => 'Gordon-Levitt', 'birth_date' => '1981-02-17', 'actor_nationality' => 'USA'],
    ['id' => 6, 'first_name' => 'Ellen', 'last_name' => 'Page', 'birth_date' => '1987-02-21', 'actor_nationality' => 'Canada'],
    ['id' => 7, 'first_name' => 'Tom', 'last_name' => 'Hanks', 'birth_date' => '1956-07-09', 'actor_nationality' => 'USA'],
    ['id' => 8, 'first_name' => 'Matt', 'last_name' => 'Damon', 'birth_date' => '1970-10-08', 'actor_nationality' => 'USA'],
    ['id' => 9, 'first_name' => 'Robert', 'last_name' => 'De Niro', 'birth_date' => '1943-08-17', 'actor_nationality' => 'USA'],
    ['id' => 10, 'first_name' => 'Al', 'last_name' => 'Pacino', 'birth_date' => '1940-04-25', 'actor_nationality' => 'USA'],
    ['id' => 11, 'first_name' => 'Sigourney', 'last_name' => 'Weaver', 'birth_date' => '1949-10-08', 'actor_nationality' => 'USA'],
    ['id' => 12, 'first_name' => 'Ian', 'last_name' => 'McKellen', 'birth_date' => '1939-05-25', 'actor_nationality' => 'UK'],
    ['id' => 13, 'first_name' => 'Elijah', 'last_name' => 'Wood', 'birth_date' => '1981-01-28', 'actor_nationality' => 'USA'],
    ['id' => 14, 'first_name' => 'Kate', 'last_name' => 'Winslet', 'birth_date' => '1975-10-05', 'actor_nationality' => 'UK'],
    ['id' => 15, 'first_name' => 'Morgan', 'last_name' => 'Freeman', 'birth_date' => '1937-06-01', 'actor_nationality' => 'USA'],
    ['id' => 16, 'first_name' => 'Russell', 'last_name' => 'Crowe', 'birth_date' => '1964-04-07', 'actor_nationality' => 'Australia'],
    ['id' => 17, 'first_name' => 'Joaquin', 'last_name' => 'Phoenix', 'birth_date' => '1974-10-28', 'actor_nationality' => 'USA'],
    ['id' => 18, 'first_name' => 'Connie', 'last_name' => 'Nielsen', 'birth_date' => '1965-07-03', 'actor_nationality' => 'Danimarca'],
    ['id' => 19, 'first_name' => 'Keanu', 'last_name' => 'Reeves', 'birth_date' => '1964-09-02', 'actor_nationality' => 'Canada'],
    ['id' => 20, 'first_name' => 'Laurence', 'last_name' => 'Fishburne', 'birth_date' => '1961-07-30', 'actor_nationality' => 'USA'],
    ['id' => 21, 'first_name' => 'Carrie-Anne', 'last_name' => 'Moss', 'birth_date' => '1967-08-21', 'actor_nationality' => 'Canada'],
    ['id' => 22, 'first_name' => 'Roberto', 'last_name' => 'Benigni', 'birth_date' => '1952-10-27', 'actor_nationality' => 'Italia'],
    ['id' => 23, 'first_name' => 'Nicoletta', 'last_name' => 'Braschi', 'birth_date' => '1953-04-19', 'actor_nationality' => 'Italia'],
    ['id' => 24, 'first_name' => 'Christian', 'last_name' => 'Bale', 'birth_date' => '1974-01-30', 'actor_nationality' => 'UK'],
    ['id' => 25, 'first_name' => 'Heath', 'last_name' => 'Ledger', 'birth_date' => '1979-04-04', 'actor_nationality' => 'Australia'],
    ['id' => 26, 'first_name' => 'Aaron', 'last_name' => 'Eckhart', 'birth_date' => '1968-03-12', 'actor_nationality' => 'USA'],
    ['id' => 27, 'first_name' => 'Matthew', 'last_name' => 'McConaughey', 'birth_date' => '1969-11-04', 'actor_nationality' => 'USA'],
    ['id' => 28, 'first_name' => 'Anne', 'last_name' => 'Hathaway', 'birth_date' => '1982-11-12', 'actor_nationality' => 'USA'],
    ['id' => 29, 'first_name' => 'Jessica', 'last_name' => 'Chastain', 'birth_date' => '1977-03-24', 'actor_nationality' => 'USA'],
    ['id' => 30, 'first_name' => 'Adrien', 'last_name' => 'Brody', 'birth_date' => '1973-04-14', 'actor_nationality' => 'USA'],
    ['id' => 31, 'first_name' => 'Jeffrey', 'last_name' => 'Lebowski', 'birth_date' => '1957-12-01', 'actor_nationality' => 'USA'],  
    ['id' => 32, 'first_name' => 'John', 'last_name' => 'Goodman', 'birth_date' => '1952-06-20', 'actor_nationality' => 'USA'],
    ['id' => 33, 'first_name' => 'Steve', 'last_name' => 'Buscemi', 'birth_date' => '1957-12-13', 'actor_nationality' => 'USA'],
    ['id' => 34, 'first_name' => 'Audrey', 'last_name' => 'Tautou', 'birth_date' => '1976-08-09', 'actor_nationality' => 'Francia'],
    ['id' => 35, 'first_name' => 'Mathieu', 'last_name' => 'Kassovitz', 'birth_date' => '1967-02-03', 'actor_nationality' => 'Francia'],
    ['id' => 36, 'first_name' => 'Ewan', 'last_name' => 'McGregor', 'birth_date' => '1971-03-31', 'actor_nationality' => 'Regno Unito'],
    ['id' => 37, 'first_name' => 'Ewen', 'last_name' => 'Bremner', 'birth_date' => '1970-12-11', 'actor_nationality' => 'Regno Unito'],
    ['id' => 38, 'first_name' => 'Jonny', 'last_name' => 'Lee Miller', 'birth_date' => '1972-11-15', 'actor_nationality' => 'Regno Unito'],
    ['id' => 39, 'first_name' => 'Ryan', 'last_name' => 'Gosling', 'birth_date' => '1980-11-12', 'actor_nationality' => 'Canada'],
    ['id' => 40, 'first_name' => 'Emma', 'last_name' => 'Stone', 'birth_date' => '1988-11-06', 'actor_nationality' => 'USA'],
    ['id' => 41, 'first_name' => 'Ryan', 'last_name' => 'Gosling', 'birth_date' => '1980-11-12', 'actor_nationality' => 'Canada'],
    ['id' => 42, 'first_name' => 'Harrison', 'last_name' => 'Ford', 'birth_date' => '1942-07-13', 'actor_nationality' => 'USA'],
    ['id' => 43, 'first_name' => 'Ana', 'last_name' => 'de Armas', 'birth_date' => '1988-04-30', 'actor_nationality' => 'Cuba'],
    ['id' => 44, 'first_name' => 'Ivana', 'last_name' => 'Baquero', 'birth_date' => '1994-06-11', 'actor_nationality' => 'Spagna'],
    ['id' => 45, 'first_name' => 'Sergi', 'last_name' => 'López', 'birth_date' => '1965-12-22', 'actor_nationality' => 'Spagna'],
    ['id' => 46, 'first_name' => 'Miles', 'last_name' => 'Teller', 'birth_date' => '1987-02-20', 'actor_nationality' => 'USA'],
    ['id' => 47, 'first_name' => 'J.K.', 'last_name' => 'Simmons', 'birth_date' => '1955-01-09', 'actor_nationality' => 'USA'],
    ['id' => 48, 'first_name' => 'Carey', 'last_name' => 'Mulligan', 'birth_date' => '1985-05-28', 'actor_nationality' => 'Regno Unito'],
    ['id' => 49, 'first_name' => 'Tobey', 'last_name' => 'Maguire', 'birth_date' => '1975-06-27', 'actor_nationality' => 'USA'],
];
