<?php
return [
    ['id' => 1, 'first_name' => 'Quentin', 'last_name' => 'Tarantino', 'birth_date' => '1963-03-27', 'director_nationality' => 'USA'],
    ['id' => 2, 'first_name' => 'Christopher', 'last_name' => 'Nolan', 'birth_date' => '1970-07-30', 'director_nationality' => 'UK'],
    ['id' => 3, 'first_name' => 'Steven', 'last_name' => 'Spielberg', 'birth_date' => '1946-12-18', 'director_nationality' => 'USA'],
    ['id' => 4, 'first_name' => 'Martin', 'last_name' => 'Scorsese', 'birth_date' => '1942-11-17', 'director_nationality' => 'USA'],
    ['id' => 5, 'first_name' => 'Ridley', 'last_name' => 'Scott', 'birth_date' => '1937-11-30', 'director_nationality' => 'UK'],
    ['id' => 6, 'first_name' => 'Peter', 'last_name' => 'Jackson', 'birth_date' => '1961-10-31', 'director_nationality' => 'Nuova Zelanda'],
    ['id' => 7, 'first_name' => 'James', 'last_name' => 'Cameron', 'birth_date' => '1954-08-16', 'director_nationality' => 'Canada'],
    ['id' => 8, 'first_name' => 'Francis Ford', 'last_name' => 'Coppola', 'birth_date' => '1939-04-07', 'director_nationality' => 'USA'],
    ['id' => 9, 'first_name' => 'Stanley', 'last_name' => 'Kubrick', 'birth_date' => '1928-07-26', 'director_nationality' => 'USA'],
    ['id' => 10, 'first_name' => 'David', 'last_name' => 'Fincher', 'birth_date' => '1962-08-28', 'director_nationality' => 'USA'],
    ['id' => 11, 'first_name' => 'Ridley', 'last_name' => 'Scott', 'birth_date' => '1937-11-30', 'director_nationality' => 'UK'],
    ['id' => 12, 'first_name' => 'Lana', 'last_name' => 'Wachowski', 'birth_date' => '1965-06-21', 'director_nationality' => 'USA'],
    ['id' => 13, 'first_name' => 'Roberto', 'last_name' => 'Benigni', 'birth_date' => '1952-10-27', 'director_nationality' => 'Italia'],
    ['id' => 14, 'first_name' => 'Christopher', 'last_name' => 'Nolan', 'birth_date' => '1970-07-30', 'director_nationality' => 'UK'],
    ['id' => 15, 'first_name' => 'Roman', 'last_name' => 'Polanski', 'birth_date' => '1933-08-18', 'director_nationality' => 'Polonia'],
    ['id' => 16, 'first_name' => 'Joel', 'last_name' => 'Coen', 'birth_date' => '1954-11-29', 'director_nationality' => 'USA'],
    ['id' => 17, 'first_name' => 'Jean-Pierre', 'last_name' => 'Jeunet', 'birth_date' => '1953-09-03', 'director_nationality' => 'Francia'],
    ['id' => 18, 'first_name' => 'Danny', 'last_name' => 'Boyle', 'birth_date' => '1956-10-20', 'director_nationality' => 'Regno Unito'],
    ['id' => 19, 'first_name' => 'Damien', 'last_name' => 'Chazelle', 'birth_date' => '1985-01-19', 'director_nationality' => 'USA'],
    ['id' => 20, 'first_name' => 'Denis', 'last_name' => 'Villeneuve', 'birth_date' => '1967-10-03', 'director_nationality' => 'Canada'],
    ['id' => 21, 'first_name' => 'Guillermo', 'last_name' => 'del Toro', 'birth_date' => '1964-10-09', 'director_nationality' => 'Messico'],
    ['id' => 22, 'first_name' => 'Damien', 'last_name' => 'Chazelle', 'birth_date' => '1985-01-19', 'director_nationality' => 'USA'],
    ['id' => 23, 'first_name' => 'Baz', 'last_name' => 'Luhrmann', 'birth_date' => '1962-09-17', 'director_nationality' => 'Australia'],
];
