<?php
return [
    [
        'id' => 1,
        'title' => 'Pulp Fiction',
        'description' => 'Un intreccio di storie criminali nel mondo di Los Angeles, raccontato con uno stile unico e dialoghi memorabili.',
        'director_id' => 1,
        'actors' => [1, 2, 3],
        'genres' => [6, 3], // Crime, Thriller (coerente)
        'poster' => 'pulp_fiction.jpg',
        'duration' => 154,
        'nationality' => 'USA',
        'slug' => 'pulp-fiction',
        'release_year' => 1994,
        'rating' => 5,
    ],
    [
        'id' => 2,
        'title' => 'Inception',
        'description' => 'Un ladro che ruba segreti entrando nei sogni viene incaricato di impiantare un’idea nella mente di una persona.',
        'director_id' => 2,
        'actors' => [4, 5, 6],
        'genres' => [4, 3], // Fantascienza, Thriller (coerente)
        'poster' => 'inception.jpg',
        'duration' => 148,
        'nationality' => 'USA',
        'slug' => 'inception',
        'release_year' => 2010,
        'rating' => 4,
    ],
    [
        'id' => 3,
        'title' => 'Forrest Gump',
        'description' => 'La straordinaria vita di Forrest Gump, un uomo semplice con un cuore grande che attraversa eventi storici degli USA.',
        'director_id' => 3,
        'actors' => [7, 8],
        'genres' => [1, 8], // Drammatico, Storico (storico per gli eventi storici)
        'poster' => 'forrest_gump.jpg',
        'duration' => 142,
        'nationality' => 'USA',
        'slug' => 'forrest-gump',
        'release_year' => 1994,
        'rating' => 5,
    ],
    [
        'id' => 4,
        'title' => 'Taxi Driver',
        'description' => 'Un tassista di New York lotta con la sua alienazione mentre si immerge nel mondo della violenza e del crimine.',
        'director_id' => 4,
        'actors' => [9, 10],
        'genres' => [1, 6], // Drammatico, Crime
        'poster' => 'taxi_driver.jpg',
        'duration' => 114,
        'nationality' => 'USA',
        'slug' => 'taxi-driver',
        'release_year' => 1976,
        'rating' => 4,
    ],
    [
        'id' => 5,
        'title' => 'Alien',
        'description' => 'L’equipaggio di una nave spaziale affronta una creatura mortale e misteriosa che li mette in pericolo vitale.',
        'director_id' => 5,
        'actors' => [11],
        'genres' => [4], // Fantascienza
        'poster' => 'alien.jpg',
        'duration' => 117,
        'nationality' => 'USA',
        'slug' => 'alien',
        'release_year' => 1979,
        'rating' => 5,
    ],
    [
        'id' => 6,
        'title' => 'Il Signore degli Anelli: La Compagnia dell’Anello',
        'description' => 'Un gruppo di eroi intraprende un viaggio epico per distruggere un anello malvagio e salvare la Terra di Mezzo.',
        'director_id' => 6,
        'actors' => [12, 13],
        'genres' => [5, 7], // Avventura, Fantasy
        'poster' => 'lotr_fellowship.jpg',
        'duration' => 178,
        'nationality' => 'Nuova Zelanda',
        'slug' => 'il-signore-degli-anelli-la-compagnia-dell-anello',
        'release_year' => 2001,
        'rating' => 5,
    ],
    [
        'id' => 7,
        'title' => 'Titanic',
        'description' => 'La tragica storia d’amore a bordo del transatlantico Titanic, con un epico sfondo storico e drammatico.',
        'director_id' => 7,
        'actors' => [4, 14],
        'genres' => [8, 10], // Storico, Romantico
        'poster' => 'titanic.jpg',
        'duration' => 195,
        'nationality' => 'USA',
        'slug' => 'titanic',
        'release_year' => 1997,
        'rating' => 4,
    ],
    [
        'id' => 8,
        'title' => 'Il Padrino',
        'description' => 'La saga della famiglia mafiosa Corleone, con intrighi, tradimenti e potere nel mondo del crimine organizzato.',
        'director_id' => 8,
        'actors' => [9, 10],
        'genres' => [6, 1], // Crime, Drammatico
        'poster' => 'il-padrino.jpg',
        'duration' => 175,
        'nationality' => 'USA',
        'slug' => 'il-padrino',
        'release_year' => 1972,
        'rating' => 5,
    ],
    [
        'id' => 9,
        'title' => '2001: Odissea nello spazio',
        'description' => 'Un viaggio enigmatico nello spazio e nel tempo, esplorando l’evoluzione umana e l’intelligenza artificiale.',
        'director_id' => 9,
        'actors' => [],
        'genres' => [4, 3], // Fantascienza, Thriller
        'poster' => '2001_odissea.jpg',
        'duration' => 149,
        'nationality' => 'USA',
        'slug' => '2001-odissea-nello-spazio',
        'release_year' => 1968,
        'rating' => 4,
    ],
    [
        'id' => 10,
        'title' => 'Fight Club',
        'description' => 'Un uomo insoddisfatto crea un club di lotta clandestino che evolve in una rivoluzione contro la società moderna.',
        'director_id' => 10,
        'actors' => [4, 15],
        'genres' => [1], // Drammatico
        'poster' => 'fight_club.jpg',
        'duration' => 139,
        'nationality' => 'USA',
        'slug' => 'fight-club',
        'release_year' => 1999,
        'rating' => 5,
    ],
    [
        'id' => 11,
        'title' => 'Gladiatore',
        'description' => 'Un generale romano diventa gladiatore per vendicare la morte della sua famiglia e combattere contro la corruzione dell’impero.',
        'director_id' => 5,
        'actors' => [16, 17, 18],
        'genres' => [8, 1], // Storico, Drammatico
        'poster' => 'gladiatore.jpg',
        'duration' => 155,
        'nationality' => 'USA',
        'slug' => 'gladiatore',
        'release_year' => 2000,
        'rating' => 5,
    ],
    [
        'id' => 12,
        'title' => 'Matrix',
        'description' => 'Un hacker scopre che la realtà è una simulazione e si unisce alla ribellione per liberare l’umanità dal controllo delle macchine.',
        'director_id' => 12,
        'actors' => [19, 20, 21],
        'genres' => [4, 3], // Fantascienza, Thriller
        'poster' => 'matrix.jpg',
        'duration' => 136,
        'nationality' => 'USA',
        'slug' => 'matrix',
        'release_year' => 1999,
        'rating' => 5,
    ],
    [
        'id' => 13,
        'title' => 'La Vita è Bella',
        'description' => 'Un padre usa l’immaginazione e l’umorismo per proteggere suo figlio dagli orrori di un campo di concentramento.',
        'director_id' => 13,
        'actors' => [22, 23],
        'genres' => [8, 9], // Storico, Commedia (anche drammatico, ma qui comico-romantico)
        'poster' => 'la-vita-e-bella.jpg',
        'duration' => 116,
        'nationality' => 'Italia',
        'slug' => 'la-vita-e-bella',
        'release_year' => 1997,
        'rating' => 5,
    ],
    [
        'id' => 14,
        'title' => 'Il Cavaliere Oscuro',
        'description' => 'Batman affronta il caos portato dal Joker nella Gotham City, mettendo in gioco la sua stessa anima.',
        'director_id' => 2,
        'actors' => [24, 25, 26],
        'genres' => [6, 1, 3], // Crime, Drammatico, Thriller
        'poster' => 'il-cavaliere-oscuro.jpg',
        'duration' => 152,
        'nationality' => 'USA',
        'slug' => 'il-cavaliere-oscuro',
        'release_year' => 2008,
        'rating' => 5,
    ],
    [
        'id' => 15,
        'title' => 'Interstellar',
        'description' => 'Un gruppo di astronauti parte per una missione attraverso un wormhole per trovare un nuovo pianeta abitabile.',
        'director_id' => 2,
        'actors' => [27, 28, 29],
        'genres' => [4, 5], // Fantascienza, Avventura
        'poster' => 'interstellar.jpg',
        'duration' => 169,
        'nationality' => 'USA',
        'slug' => 'interstellar',
        'release_year' => 2014,
        'rating' => 5,
    ],
    [
        'id' => 16,
        'title' => 'Il Pianista',
        'description' => 'La lotta per la sopravvivenza di un pianista ebreo durante l’occupazione nazista di Varsavia.',
        'director_id' => 15,
        'actors' => [30],
        'genres' => [8, 1], // Storico, Drammatico
        'poster' => 'il-pianista.jpg',
        'duration' => 150,
        'nationality' => 'Polonia',
        'slug' => 'il-pianista',
        'release_year' => 2002,
        'rating' => 5,
    ],
    [
        'id' => 17,
        'title' => 'Il Grande Lebowski',
        'description' => 'Le vicende di un uomo pigro e rilassato che si ritrova coinvolto in un caso di rapimento e fraintendimenti assurdi.',
        'director_id' => 16,
        'actors' => [31, 32, 33],
        'genres' => [9, 2], // Commedia, Azione (è una commedia con elementi d’azione)
        'poster' => 'il-grande-lebowski.jpg',
        'duration' => 117,
        'nationality' => 'USA',
        'slug' => 'il-grande-lebowski',
        'release_year' => 1998,
        'rating' => 4,
    ],
    [
        'id' => 18,
        'title' => 'Amélie',
        'description' => 'Una giovane donna decide di cambiare la vita delle persone intorno a lei con gesti gentili e fantasiosi.',
        'director_id' => 17,
        'actors' => [34, 35],
        'genres' => [9, 10], // Commedia, Romantico
        'poster' => 'amelie.jpg',
        'duration' => 122,
        'nationality' => 'Francia',
        'slug' => 'amelie',
        'release_year' => 2001,
        'rating' => 4,
    ],
    [
        'id' => 19,
        'title' => 'Trainspotting',
        'description' => 'Le vicende di un gruppo di giovani scozzesi alle prese con la dipendenza da eroina e la vita di strada.',
        'director_id' => 18,
        'actors' => [36, 37, 38],
        'genres' => [9, 10], // Commedia, Romantico
        'poster' => 'trainspotting.jpg',
        'duration' => 94,
        'nationality' => 'Regno Unito',
        'slug' => 'trainspotting',
        'release_year' => 1996,
        'rating' => 4,
    ],
    [
        'id' => 20,
        'title' => 'La La Land',
        'description' => 'Una storia d’amore tra un musicista jazz e un’aspirante attrice nella vibrante città di Los Angeles.',
        'director_id' => 19,
        'actors' => [39, 40],
        'genres' => [9, 10], // Commedia, Romantico (musical-romantico)
        'poster' => 'la-la-land.jpg',
        'duration' => 128,
        'nationality' => 'USA',
        'slug' => 'la-la-land',
        'release_year' => 2016,
        'rating' => 4,
    ],
    [
        'id' => 21,
        'title' => 'Blade Runner 2049',
        'description' => 'Un nuovo blade runner scopre un segreto che potrebbe far precipitare ciò che resta della società.',
        'director_id' => 20,
        'actors' => [41, 42, 43],
        'genres' => [4, 3], // Fantascienza, Thriller
        'poster' => 'blade_runner_2049.jpg',
        'duration' => 164,
        'nationality' => 'USA',
        'slug' => 'blade-runner-2049',
        'release_year' => 2017,
        'rating' => 5,
    ],
    [
        'id' => 22,
        'title' => 'Il Labirinto del Fauno',
        'description' => 'Una ragazza scopre un mondo fantastico e oscuro durante la guerra civile spagnola.',
        'director_id' => 21,
        'actors' => [44, 45],
        'genres' => [7, 8], // Fantasy, Storico
        'poster' => 'il-labirinto-del-fauno.jpg',
        'duration' => 118,
        'nationality' => 'Spagna',
        'slug' => 'il-labirinto-del-fauno',
        'release_year' => 2006,
        'rating' => 5,
    ],
    [
        'id' => 23,
        'title' => 'Whiplash',
        'description' => 'Un giovane batterista jazz lotta per raggiungere la perfezione sotto la guida di un insegnante esigente e crudele.',
        'director_id' => 19,
        'actors' => [46, 47],
        'genres' => [2, 1], // Azione (per intensità), Drammatico
        'poster' => 'whiplash.jpg',
        'duration' => 106,
        'nationality' => 'USA',
        'slug' => 'whiplash',
        'release_year' => 2014,
        'rating' => 5,
    ],
    [
        'id' => 24,
        'title' => 'Il Grande Gatsby',
        'description' => 'La storia tragica di un uomo ricco e misterioso e del suo amore impossibile negli anni ruggenti.',
        'director_id' => 23,
        'actors' => [48, 49],
        'genres' => [1, 10], // Drammatico, Romantico
        'poster' => 'il-grande-gatsby.jpg',
        'duration' => 143,
        'nationality' => 'USA',
        'slug' => 'il-grande-gatsby',
        'release_year' => 2013,
        'rating' => 4,
    ],
];
